package autonoma.furiaenlacarretera.views;
import autonoma.furiaenlacarretera.ui.GameWindow;
import autonoma.furiaenlacarretera.elements.GameField;
import autonoma.furiaenlacarretera.sounds.ReproducirSonido;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Kamii
 */
public class VentanaInicial extends JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        ReproducirSonido.playSound("sonidoInicio.wav");
        
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/carroBugatti.png")).getImage());
        }catch(Exception e){
            System.out.println("imagen no encontrada");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 194, 2));

        jPanel2.setBackground(new java.awt.Color(48, 194, 2));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/furiaenlacarretera/images/FondoPrincipal.png"))); // NOI18N

        btnPlay.setBackground(new java.awt.Color(48, 194, 2));
        btnPlay.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btnPlay.setText("PLAY!");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnPlay)
                .addGap(203, 203, 203))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlay)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        iniciarJuego();
    }//GEN-LAST:event_btnPlayMouseClicked
    /**
     * Este método inicializa y configura el juego al hacer clic en el botón
     * "JUGAR". Crea una nueva instancia de los objetos necesarios para iniciar
     * la partida, configura la ventana de juego y muestra el campo de batalla
     * con el jugador. Después de iniciar el juego, cierra la ventana de inicio.
     */
    private void iniciarJuego() {
        GameField gameField = new GameField(0, 0, 500, 500);
        
        //Player player = new Player(armaInicial, 100, 100, 50, 50);
        //battlefield.setPlayer(player);

        GameWindow window = new GameWindow(gameField);
        //battlefield.setGraphicContainer(window);

        window.setSize(500, 500);
        window.setTitle("Furia en la carretera");
        window.setLocationRelativeTo(null);
        window.setVisible(true);

        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
